terraform, ansible 15

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -30,9 +30,13 @@ jobs:
 
       - name: Save EC2 Public IP
         run: |
-          echo 'EC2_IP<<EOF' >> $GITHUB_ENV
-          terraform output -raw ec2_public_ip >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
+          EC2_IP=$(terraform output -raw ec2_public_ip 2>/dev/null || echo "NOT_SET")
+          if [ "$EC2_IP" == "NOT_SET" ]; then
+            echo "EC2 Public IP not found! Deployment cannot proceed."
+            exit 1
+          fi
+          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
+          working-directory: terraform
 
 
   ansible:
