terraform, ansible 24

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -32,7 +32,11 @@ jobs:
 
       - name: Save EC2 Public IP
         run: |
-          EC2_IP=$(terraform output -raw ec2_public_ip)
+          EC2_IP=$(terraform output -raw ec2_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+          if [ -z "$EC2_IP" ]; then
+            echo "EC2 Public IP not found! Deployment cannot proceed."
+            exit 1
+          fi
           echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
         working-directory: terraform
 
